### ISSUE TITLE
Deploy Episcreamer to serverless

### ISSUE THREAD

**Issue by rulio** [glg/serverless-buildpack#6]

**Comment by rulio** [comment]
Need help from @igroff to update IAM policy that relates to serverless buildpack.  

Serverless buildpack must specify the role that will be used by the Lambda function.  Currently IAM permissions restrict it to passing only one specific role along to Lambda.  The relevant IAM policy is: `arn:aws:iam::868468680417:policy/lambda-deploy-pass-lambda-function-role` , which allows only the role `arn:aws:iam::*:role/lambda-deploy-function-role` to be passed.

Epi screamer needs to specify it's own custom role.  This is supported in serverless buildpack but its attempt to pass the role fails due to lacking permissions.  To resolve this we modify the above policy to:
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": "iam:PassRole",
            "Resource": [
				"arn:aws:iam::*:role/lambda-deploy-function-role",
				"arn:aws:iam::*:role/serverless-*”
			]
        }
    ]
}
```
This will allow serverless buildpack to pass any role to Lambda that begins with `serverless-`.

Second we would need to create a new role for epi-screamer that uses the same policy as its current `role: arn:aws:iam::868468680417:policy/s3_epi_screamer`.  The new role should be named something like: `serverless-s3_epi_screamer`

**Comment by igroff** [comment]
Done, in a room, with the candlestick and Raul.
